//
//  Spaceship+JsonGen.swift
//
//  Auto generated by swift-json-gen on Tue, 18 Aug 2015 19:21:49 GMT
//

import Foundation

extension Spaceship {
  static func decodeJson(json: AnyObject) -> Spaceship? {
    let _dict = json as? [String : AnyObject]
    if _dict == nil { return nil }
    let dict = _dict!

    let id_field: AnyObject? = dict["_id"]
    if id_field == nil { assertionFailure("field 'id' is missing"); return nil }
    let id_optional: String? = String.decodeJson(id_field!)
    if id_optional == nil { assertionFailure("field 'id' is not String"); return nil }
    let id: String = id_optional!

    let pictureDriver_field: AnyObject? = dict["pictureDriver"]
    if pictureDriver_field == nil { assertionFailure("field 'pictureDriver' is missing"); return nil }
    let pictureDriver_optional: NSURL? = NSURL.decodeJson(pictureDriver_field!)
    if pictureDriver_optional == nil { assertionFailure("field 'pictureDriver' is not NSURL"); return nil }
    let pictureDriver: NSURL = pictureDriver_optional!

    let nameDriver_field: AnyObject? = dict["nameDriver"]
    if nameDriver_field == nil { assertionFailure("field 'nameDriver' is missing"); return nil }
    let nameDriver_optional: String? = String.decodeJson(nameDriver_field!)
    if nameDriver_optional == nil { assertionFailure("field 'nameDriver' is not String"); return nil }
    let nameDriver: String = nameDriver_optional!

    let specie_field: AnyObject? = dict["specie"]
    if specie_field == nil { assertionFailure("field 'specie' is missing"); return nil }
    let specie_optional: String? = String.decodeJson(specie_field!)
    if specie_optional == nil { assertionFailure("field 'specie' is not String"); return nil }
    let specie: String = specie_optional!

    let planet_field: AnyObject? = dict["planet"]
    if planet_field == nil { assertionFailure("field 'planet' is missing"); return nil }
    let planet_optional: String? = String.decodeJson(planet_field!)
    if planet_optional == nil { assertionFailure("field 'planet' is not String"); return nil }
    let planet: String = planet_optional!

    let pictureSpaceship_field: AnyObject? = dict["pictureSpaceship"]
    if pictureSpaceship_field == nil { assertionFailure("field 'pictureSpaceship' is missing"); return nil }
    let pictureSpaceship_optional: NSURL? = NSURL.decodeJson(pictureSpaceship_field!)
    if pictureSpaceship_optional == nil { assertionFailure("field 'pictureSpaceship' is not NSURL"); return nil }
    let pictureSpaceship: NSURL = pictureSpaceship_optional!

    let typeSpaceship_field: AnyObject? = dict["typeSpaceship"]
    if typeSpaceship_field == nil { assertionFailure("field 'typeSpaceship' is missing"); return nil }
    let typeSpaceship_optional: String? = String.decodeJson(typeSpaceship_field!)
    if typeSpaceship_optional == nil { assertionFailure("field 'typeSpaceship' is not String"); return nil }
    let typeSpaceship: String = typeSpaceship_optional!

    return Spaceship(id: id, pictureDriver: pictureDriver, nameDriver: nameDriver, specie: specie, planet: planet, pictureSpaceship: pictureSpaceship, typeSpaceship: typeSpaceship)
  }

  func encodeJson() -> AnyObject {
    var dict: [String: AnyObject] = [:]

    dict["_id"] = id.encodeJson()
    dict["pictureDriver"] = pictureDriver.encodeJson()
    dict["nameDriver"] = nameDriver.encodeJson()
    dict["specie"] = specie.encodeJson()
    dict["planet"] = planet.encodeJson()
    dict["pictureSpaceship"] = pictureSpaceship.encodeJson()
    dict["typeSpaceship"] = typeSpaceship.encodeJson()

    return dict
  }
}
